
project_id = "lxsuqqlfuftnvuvtctsx"

[functions.grade-user-submissions]
verify_jwt = true

[functions.stripe-subscription-webhook]
verify_jwt = false

[functions.crons]
grade_submissions = "0 19 * * *" # Run daily at 7 PM

