
project_id = "YOUR-PROJECT-ID"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.fetch-ga4-metrics]
verify_jwt = true

[functions.test-connection]
verify_jwt = true

# Add CRON schedule for GA4 metrics fetch
[functions.fetch-ga4-metrics.cron]
schedule = "0 4 * * *"  # Run at 4 AM daily

