
project_id = "lxsuqqlfuftnvuvtctsx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true

[storage]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = false

[vector]
enabled = true

# Edge Functions Configuration
[functions]
[functions.manage-billing]
verify_jwt = true

[functions.billing-database-setup]
verify_jwt = false
