
project_id = "lxsuqqlfuftnvuvtctsx"

[functions.execute-agent-task]
verify_jwt = true

[functions.retry-agent-tasks]
verify_jwt = true

[functions.check-kpi-alerts]
verify_jwt = true

[functions.twilio-send-sms]
verify_jwt = true

[functions.generate-alert-suggestions]
verify_jwt = true
