
# This is your Supabase project configuration file
project_id = "lxsuqqlfuftnvuvtctsx"

[api]
# Enabled APIs for this project. By default all APIs are enabled, but you can disable some if needed.
enabled = ["rest", "graphql", "realtime"]

[db]
# Port on which the shell will connect to the database.
port = 5432
shadow_port = 5433

[auth]
# For more information on JWT settings, see https://supabase.com/docs/reference/tools/auth
jwt_secret = ""

[db.pooler]
enabled = false
port = 5432
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100
pool_size = 100

[realtime]
enabled = true
webhook_enabled = true
webhook_callback = "https://lxsuqqlfuftnvuvtctsx.functions.supabase.co/listen-realtime"
webhook_format = "json"
webhook_headers = ["X-Webhook-Source:supabase"]

[functions]
check-kpi-alerts = { verify_jwt = true }
fetch-kpi-trend = { verify_jwt = true }
refresh-tokens = { verify_jwt = true }
retry-runner = { verify_jwt = true }
send-alert-digest = { verify_jwt = true }
update-mql-metrics = { verify_jwt = true }
reset-demo-tenant = { verify_jwt = true }
stripe-usage-reporter = { verify_jwt = true }
stripe-invoice-webhook = { verify_jwt = false }
stripe-subscription-webhook = { verify_jwt = false }
stripe-payout-webhook = { verify_jwt = false }
send-webhook-notification = { verify_jwt = true }
send-webhook-alert = { verify_jwt = true }
send-credit-digest = { verify_jwt = true }
decrementCredits = { verify_jwt = true }
generate-alert-suggestions = { verify_jwt = true }
manage-billing = { verify_jwt = true }

[storage]
file_size_limit = "50MiB"
