
project_id = "lxsuqqlfuftnvuvtctsx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.fetch-ga4-metrics]
verify_jwt = true

[functions.test-connection]
verify_jwt = true

[functions.strategy-adjustments]
verify_jwt = true

[functions.send-alert-digest]
verify_jwt = true
schedule = "0 9 * * MON"  # Run at 9 AM every Monday

# Add CRON schedule for GA4 metrics fetch
[functions.fetch-ga4-metrics.cron]
schedule = "0 4 * * *"  # Run at 4 AM daily

# Add CRON schedule for strategy adjustments
[functions.strategy-adjustments.cron]
schedule = "0 6 * * MON"  # Run at 6 AM every Monday
