
project_id = "YOUR-PROJECT-ID"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.generate-strategy]
verify_jwt = true
