
project_id = "lxsuqqlfuftnvuvtctsx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
inmemory = false

[inbucket]
enabled = false
port = 54324

[auth]
enabled = true
port = 54325

[storage]
enabled = true

[realtime]
enabled = true

[functions.check-rls-policies]
verify_jwt = true

[functions.check-secrets]
verify_jwt = true

[functions.save-onboarding]
verify_jwt = true

[functions.create-system-tables]
verify_jwt = true

[vector]
enabled = true

