
project_id = "lxsuqqlfuftnvuvtctsx"

[api]
enabled = true

[api.cors]
enabled = false

[db]
port = 5432
shadow_port = 5433

[db.pooler]
enabled = false
port = 6432
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 6969

[inbucket]
enabled = true
port = 6543

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true

[edge-functions]
enabled = true

[edge-functions.fetch-ga4-metrics]
verify_jwt = true

[edge-functions.check-kpi-alerts]
verify_jwt = true

[edge-functions.fetch-kpi-trend]
verify_jwt = true

[edge-functions.update-mql-metrics]
verify_jwt = true
