
# Config file for our Supabase project
project_id = "lxsuqqlfuftnvuvtctsx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[realtime]
enabled = true

# Our edge functions
[functions.security_audit]
verify_jwt = true

[functions.check-table-rls-status]
verify_jwt = true

[functions.check-rls-policies]
verify_jwt = true

[functions.generate-strategy]
verify_jwt = true

[functions.generate-campaign]
verify_jwt = true

[functions.check-subscription]
verify_jwt = false

[functions.strategy-init]
verify_jwt = true
