
import LegalLayout from "@/components/layouts/LegalLayout";

export default function AIDisclosure() {
  return (
    <LegalLayout title="AI Usage Terms">
      <div className="space-y-6">
        <div className="mb-8">
          <p className="text-sm text-muted-foreground">Effective Date: April 21, 2025</p>
          <p className="text-sm text-muted-foreground">Entity: ALLORA APP</p>
          <p className="text-sm text-muted-foreground">Compliant with OpenAI, LLM Guidelines</p>
        </div>

        <section className="space-y-4">
          <h2 className="text-lg font-semibold">Definitions</h2>
          <ul className="list-disc list-inside space-y-2 pl-4">
            <li>"Input": data you provide to Allora AI agents</li>
            <li>"Output": content generated by our AI tools (strategy, captions, campaign scripts)</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">Ownership</h2>
          <p>You retain rights to all Input and Output. We do not use your data to train third-party 
          AI models (e.g., OpenAI).</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">Usage Limits</h2>
          <p>AI usage may be restricted by your plan tier. Excessive usage may require an upgrade 
          or throttling.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">Limitations</h2>
          <p>Outputs are AI-generated and may contain factual inaccuracies. You must review before use.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">Prohibited Uses:</h2>
          <ul className="list-disc list-inside space-y-2 pl-4">
            <li>Misinformation, fraud, or impersonation</li>
            <li>Medical, financial, legal claims without disclaimers</li>
            <li>Large-scale AI training or derivative models</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">AI Partners</h2>
          <ul className="list-disc list-inside space-y-2 pl-4">
            <li>OpenAI</li>
            <li>LangChain</li>
            <li>Supabase Edge Functions</li>
          </ul>
        </section>
      </div>
    </LegalLayout>
  );
}
