
import { useState, useCallback } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useTenant } from "@/hooks/useTenant";
import { AgentFeedback } from "@/types/agent";
import { toast } from "sonner";

export interface FeedbackFormData {
  agent?: string;
  from_agent?: string;
  to_agent?: string;
  strategy_id?: string;
  campaign_id?: string;
  feedback?: string;
  rating?: number;
  type?: string;
  task_id?: string;
}

export function useAgentFeedback() {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [feedback, setFeedback] = useState<AgentFeedback[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const { tenant } = useTenant();

  const getFeedback = useCallback(async (agent: string) => {
    if (!tenant?.id) return [];
    
    setIsLoading(true);
    try {
      const { data, error } = await supabase
        .from("agent_feedback")
        .select("*")
        .eq("tenant_id", tenant.id)
        .eq("agent", agent)
        .order("created_at", { ascending: false });

      if (error) throw error;
      
      // Explicitly cast the data to AgentFeedback[]
      const typedFeedback = data as AgentFeedback[];
      setFeedback(typedFeedback);
      return typedFeedback;
    } catch (error) {
      console.error("Error fetching agent feedback:", error);
      return [];
    } finally {
      setIsLoading(false);
    }
  }, [tenant?.id]);

  const submitFeedback = useCallback(async (feedbackData: FeedbackFormData) => {
    if (!tenant?.id) {
      toast.error("No active workspace");
      return false;
    }

    setIsSubmitting(true);
    try {
      // Ensure agent field is set for backward compatibility
      const agentValue = feedbackData.agent || feedbackData.to_agent;
      
      if (!agentValue) {
        throw new Error("Agent field is required");
      }
      
      // Prepare the data with required fields
      const insertData: AgentFeedback = {
        id: '', // Will be generated by Supabase
        agent: agentValue,
        tenant_id: tenant.id,
        created_at: new Date().toISOString(),
        // Add other fields from feedbackData
        feedback: feedbackData.feedback,
        rating: feedbackData.rating,
        type: feedbackData.type,
        task_id: feedbackData.task_id,
        from_agent: feedbackData.from_agent,
        to_agent: feedbackData.to_agent,
      };
      
      const { error } = await supabase
        .from("agent_feedback")
        .insert(insertData as any);

      if (error) throw error;
      
      toast.success("Feedback submitted successfully");
      return true;
    } catch (error) {
      console.error("Error submitting feedback:", error);
      toast.error("Failed to submit feedback");
      return false;
    } finally {
      setIsSubmitting(false);
    }
  }, [tenant?.id]);

  return {
    feedback,
    isLoading,
    isSubmitting,
    getFeedback,
    submitFeedback
  };
}
