
name: Deploy Allora OS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Deploy database
        run: supabase db push --project-ref $SUPABASE_PROJECT_ID

      - name: Deploy edge functions
        run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID --all
